name: task1 CI

on:
  push:
    branches: main

env:
  WORKDIR: ./task1

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: isshlyapin/ubuntu_cpp:0.2
      volumes:
        - /etc/localtime:/etc/localtime
    steps:
      - name: Setup correct $HOME
        run: |
          export HOME=$(getent passwd $USER | cut -d: -f6)

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        working-directory: ${{ env.WORKDIR }}
        run: ./scripts/build.sh
      
      - name: Run tests
        working-directory: ${{ env.WORKDIR }}
        run: ./scripts/test.sh
